/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123586-g711b1a52bd-20260322"
#endif /* AVUTIL_FFVERSION_H */
